### ISSUE TITLE
unreachable condition in the CarList component

### ISSUE THREAD

**Issue by Zhaoyu-Qu** [PacktPublishing/Full-Stack-Development-with-Spring-Boot-3-and-React-Fourth-Edition#9]
In the React frontend in the CarList.tsx file, we have the following code
...
  const { data, error, isSuccess } = useQuery({
    queryKey: ["cars"],
    queryFn: getCars
  });
...
  if (!isSuccess) {
    return <span>Loading...</span>
  }
  else if (error) {
    return <span>Error when fetching cars...</span>
  }
  else {
...

However, the `else if (error)` condition is unreachable, because the (!isSuccess) condition is always met first in the event of errors, effectively shadowing the error condition.

I suggest the following changes:

...
  const { data, isSuccess, isError, isLoading } = useQuery({
    queryKey: ["cars"],
    queryFn: getCars
  });
...
  if (isLoading) {
    return <span>Loading...</span>
  }
  else if (isError) {
    return <span>Error when fetching cars...</span>
  }
  else if (isSuccess) {
...

**Comment by juhahinkula** [comment]
Yes, thanks for pointing this out. I will fix the code.
